name: Feature request
description: A new pour for the menu :3
title: "[feat] "
labels: [enhancement]
body:
  - type: textarea
    id: what
    attributes:
      label: What would you like?
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why does it matter?
      description: Which client or workflow would this unblock?
    validations:
      required: false
